"use client";

import { FormEvent, useState } from "react";
import Link from "next/link";
import AppShell from "@/components/layout/AppShell";
import WorkerProfileContent from "@/components/operations/WorkerProfileContent";
import { EmptyState, PageHeader, RecordLink, StatCard, StatusPill } from "@/components/operations/Primitives";
import { mockStore } from "@/lib/mockStore";
import { useDemoRevision } from "@/hooks/useDemoRevision";

type Surface = "manager" | "control-room" | "admin";


function WorkersList({ basePath }: { basePath: string }) {
  useDemoRevision();
  const [query, setQuery] = useState("");
  const [status, setStatus] = useState("ALL");
  const [page, setPage] = useState(0);
  const workers = mockStore.getWorkers();
  const bands = mockStore.getBands();
  const filtered = workers.filter((worker) => (status === "ALL" || worker.status === status) && `${worker.full_name} ${worker.worker_code} ${worker.department || ""}`.toLowerCase().includes(query.toLowerCase()));
  const pageSize = 6;
  const pageCount = Math.max(1, Math.ceil(filtered.length / pageSize));
  const rows = filtered.slice(page * pageSize, page * pageSize + pageSize);

  return <><PageHeader eyebrow="Company-scoped roster" title="Workers" description="Workers are managed records, not login accounts. Search, filter, and open their non-overlapping shift history." action={basePath === "/manager" ? { href: "/manager/workers/new", label: "Register worker" } : undefined}/><div className="card mb-5 grid gap-3 sm:grid-cols-[1fr_200px]"><input className="input" value={query} onChange={(event) => { setQuery(event.target.value); setPage(0); }} placeholder="Search name, code, or department" aria-label="Search workers"/><select className="input" value={status} onChange={(event) => { setStatus(event.target.value); setPage(0); }} aria-label="Filter worker status"><option value="ALL">All statuses</option><option value="ACTIVE">Active</option><option value="ON_LEAVE">On leave</option></select></div><div className="card overflow-hidden p-0"><div className="overflow-x-auto"><table className="data-table min-w-[760px]"><thead><tr><th>Worker</th><th>Department</th><th>Designation</th><th>Active band</th><th>Status</th><th>History</th></tr></thead><tbody>{rows.map((worker) => { const band = bands.find((item) => item.worker_id === worker.id && ["ACTIVE", "WARNING"].includes(item.status || "")); return <tr key={worker.id}><td><RecordLink href={`/workers/${worker.id}`}>{worker.full_name}</RecordLink><div className="text-xs text-muted">{worker.worker_code}</div></td><td>{worker.department || "—"}</td><td>{worker.designation || "—"}</td><td>{band ? <><span className="text-sm">{band.band_code}</span> <StatusPill value={band.status}/></> : "—"}</td><td><StatusPill value={worker.status}/></td><td><RecordLink href={`/workers/${worker.id}`}>Open</RecordLink></td></tr>; })}</tbody></table></div><div className="flex items-center justify-between border-t border-border px-5 py-4 text-sm"><span className="text-muted">Page {page + 1} of {pageCount} · {filtered.length} records</span><div className="flex gap-2"><button className="btn-secondary py-2" disabled={page === 0} onClick={() => setPage((value) => value - 1)}>Previous</button><button className="btn-secondary py-2" disabled={page + 1 >= pageCount} onClick={() => setPage((value) => value + 1)}>Next</button></div></div></div></>;
}

function NewWorker() {
  const [message, setMessage] = useState("");
  const [error, setError] = useState("");
  const submit = (event: FormEvent<HTMLFormElement>) => {
    event.preventDefault(); setMessage(""); setError("");
    const data = new FormData(event.currentTarget);
    const workerCode = String(data.get("worker_code") || "").trim().toUpperCase();
    if (mockStore.getWorkerById(workerCode)) { setError("Worker code already exists within the demo company."); return; }
    const worker = mockStore.registerWorker({ worker_code: workerCode, full_name: String(data.get("full_name") || "").trim(), department: String(data.get("department") || "Operations"), designation: String(data.get("designation") || "Field Technician"), default_work_area_id: String(data.get("work_area") || "AREA-COKER-01") });
    setMessage(`Worker ${worker.full_name} was registered. Issue a band before starting a shift.`); event.currentTarget.reset();
  };
  return <><PageHeader eyebrow="Shift Manager" title="Register worker" description="Create a company-scoped worker record. This does not create a login account."/><form className="card mx-auto max-w-2xl space-y-5" onSubmit={submit}><div className="grid gap-4 sm:grid-cols-2"><div><label className="label" htmlFor="full-name">Full name</label><input id="full-name" name="full_name" className="input" required/></div><div><label className="label" htmlFor="worker-code">Worker code</label><input id="worker-code" name="worker_code" className="input uppercase" required/></div><div><label className="label" htmlFor="department">Department</label><input id="department" name="department" className="input" required/></div><div><label className="label" htmlFor="designation">Designation</label><input id="designation" name="designation" className="input"/></div><div className="sm:col-span-2"><label className="label" htmlFor="work-area">Default work area</label><select id="work-area" name="work_area" className="input"><option value="AREA-COKER-01">North Plant · Coker 01</option><option value="AREA-SRU-01">North Plant · Sulfur Recovery 01</option><option value="AREA-ALK-01">South Plant · Alkylation 01</option></select></div></div>{error && <p className="rounded-lg bg-red-50 p-3 text-sm text-red-800" role="alert">{error}</p>}{message && <p className="rounded-lg bg-teal-pale p-3 text-sm text-teal" role="status">{message}</p>}<button className="btn-primary" type="submit">Register worker</button></form></>;
}

function BandsPage({ surface, detailId }: { surface: Surface; detailId?: string }) {
  useDemoRevision();
  const [workerId, setWorkerId] = useState(""); const [bandCode, setBandCode] = useState(""); const [confirmed, setConfirmed] = useState(false); const [message, setMessage] = useState(""); const [error, setError] = useState("");
  const bands = mockStore.getBands(); const workers = mockStore.getWorkers();
  if (detailId) { const band = mockStore.getBandById(detailId); if (!band) return <EmptyState title="Band not found" detail="The band identifier is invalid or outside company scope."/>; const owner = band.worker_id ? mockStore.getWorkerById(band.worker_id) : undefined; const shifts = mockStore.getShifts().filter((shift) => shift.band_id === band.id); return <><PageHeader eyebrow="Band record" title={band.band_code} description={`Batch ${band.batch_id || "unknown"} · ${band.working_day_count || 0}/5 working days`}/><div className="grid gap-4 sm:grid-cols-3"><StatCard label="Status" value={(band.status || "UNKNOWN").replaceAll("_", " ")} note={band.retirement_reason || "No retirement reason"}/><StatCard label="Cumulative estimate" value={`${band.current_cumulative_low ?? "—"}–${band.current_cumulative_high ?? "—"}`} note="Synthetic ppm·h · latest reading, never summed"/><StatCard label="Owner" value={owner?.worker_code || "Unassigned"} note={owner?.full_name || "No worker assignment"}/></div><section className="card mt-6"><h2 className="text-heading-3 text-charcoal">Shift history</h2><div className="mt-4 overflow-x-auto"><table className="data-table min-w-[620px]"><thead><tr><th>Shift</th><th>Status</th><th>Started</th><th>Increment</th></tr></thead><tbody>{shifts.map((shift) => <tr key={shift.id}><td>{shift.id}</td><td><StatusPill value={shift.status}/></td><td>{new Date(shift.started_at || "").toLocaleString("en-IN")}</td><td>{shift.exposure_low == null ? "Pending/invalid" : `${shift.exposure_low}–${shift.exposure_high} ppm·h`}</td></tr>)}</tbody></table></div></section></>; }
  const issue = (event: FormEvent) => { event.preventDefault(); setMessage(""); setError(""); try { const band = mockStore.assignBand(workerId, bandCode.trim().toUpperCase(), "BATCH-2026-Q1", confirmed); setMessage(`${band.band_code} is now permanently assigned. Any confirmed previous active band was retired; worker history was preserved.`); setBandCode(""); setConfirmed(false); } catch (caught) { setError(caught instanceof Error ? caught.message : "Band could not be issued."); } };
  return <><PageHeader eyebrow="Lifecycle" title="Bands" description="Five working days is a configurable prototype policy. Calendar use-by and condition checks are independent."/><div className={`grid gap-6 ${surface === "manager" ? "xl:grid-cols-[1fr_1.5fr]" : ""}`}>{surface === "manager" && <form className="card h-fit space-y-4" onSubmit={issue}><h2 className="text-heading-3 text-charcoal">Issue or replace band</h2><p className="text-sm text-muted">Assignment is permanent. Replacement preserves the same worker’s earlier history.</p><label className="label" htmlFor="issue-worker">Worker</label><select id="issue-worker" className="input" value={workerId} onChange={(event) => setWorkerId(event.target.value)} required><option value="">Select worker</option>{workers.map((worker) => <option key={worker.id} value={worker.id}>{worker.worker_code} · {worker.full_name}</option>)}</select><label className="label" htmlFor="issue-band">Band code</label><input id="issue-band" className="input uppercase" value={bandCode} onChange={(event) => setBandCode(event.target.value)} placeholder="BND-2001" required/><label className="flex items-start gap-3 text-sm text-charcoal"><input type="checkbox" className="mt-1" checked={confirmed} onChange={(event) => setConfirmed(event.target.checked)}/><span>I confirm permanent assignment and, if necessary, retirement of the worker’s current band.</span></label>{error && <p className="rounded-lg bg-red-50 p-3 text-sm text-red-800">{error}</p>}{message && <p className="rounded-lg bg-teal-pale p-3 text-sm text-teal">{message}</p>}<button className="btn-primary" disabled={!confirmed}>Issue band</button></form>}<div className="card overflow-hidden p-0"><div className="overflow-x-auto"><table className="data-table min-w-[760px]"><thead><tr><th>Band</th><th>Worker</th><th>Batch</th><th>Days</th><th>Condition</th><th>Details</th></tr></thead><tbody>{bands.map((band) => { const worker = band.worker_id ? mockStore.getWorkerById(band.worker_id) : undefined; return <tr key={band.id}><td className="font-medium text-charcoal">{band.band_code}</td><td>{worker ? <RecordLink href={`/workers/${worker.id}`}>{worker.full_name}</RecordLink> : "Unassigned"}</td><td>{band.batch_id || "—"}</td><td>{band.working_day_count || 0}/5</td><td><StatusPill value={band.status}/></td><td><RecordLink href={`/control-room/bands/${band.id}`}>Open</RecordLink></td></tr>; })}</tbody></table></div></div></div></>;
}

function ShiftsPage({ detailId }: { detailId?: string }) {
  useDemoRevision(); const shifts = mockStore.getShifts(); const readings = mockStore.getReadings();
  if (detailId) { const shift = shifts.find((item) => item.id === detailId); if (!shift) return <EmptyState title="Shift not found" detail="The record may have been removed or is outside company scope."/>; const worker = mockStore.getWorkerById(shift.worker_id); const paired = readings.filter((reading) => reading.shift_id === shift.id); return <><PageHeader eyebrow="Shift record" title={shift.id} description={`${worker?.full_name || shift.worker_id} · ${shift.work_area_id || "Location unavailable"}`}/><div className="grid gap-4 sm:grid-cols-3"><StatCard label="Status" value={shift.status || "UNKNOWN"} note={shift.ended_at ? `Ended ${new Date(shift.ended_at).toLocaleString("en-IN")}` : "End reading pending"}/><StatCard label="Shift increment" value={shift.confidence === "INVALID" ? "INVALID" : shift.exposure_low == null ? "Pending" : `${shift.exposure_low}–${shift.exposure_high}`} note={shift.confidence === "INVALID" ? "Not zero; manual review required" : "Synthetic ppm·h"}/><StatCard label="Confidence" value={shift.confidence || "PENDING"} note="Paired reading assessment"/></div><section className="card mt-6"><h2 className="text-heading-3 text-charcoal">Paired readings</h2><div className="mt-4 space-y-3">{paired.map((reading) => <Link key={reading.id} href={`/manager/reading/${reading.id}`} className="flex items-center justify-between rounded-lg border border-border p-4 hover:border-border-strong"><div><p className="font-medium text-charcoal">{reading.reading_type} · {reading.id}</p><p className="text-xs text-muted">{new Date(reading.captured_at || "").toLocaleString("en-IN")} · ΔE {reading.delta_e ?? "—"}</p></div><StatusPill value={reading.confidence}/></Link>)}</div></section></>; }
  return <><PageHeader eyebrow="Operations records" title="Shifts" description="Every completed record is derived from one start and one end reading. Missing baselines and invalid differences stay visible."/><div className="card overflow-hidden p-0"><div className="overflow-x-auto"><table className="data-table min-w-[820px]"><thead><tr><th>Shift</th><th>Worker</th><th>Started</th><th>Location</th><th>Status</th><th>Increment</th><th>Details</th></tr></thead><tbody>{shifts.map((shift) => { const worker = mockStore.getWorkerById(shift.worker_id); return <tr key={shift.id}><td>{shift.id}</td><td>{worker ? <RecordLink href={`/workers/${worker.id}`}>{worker.full_name}</RecordLink> : shift.worker_id}</td><td>{new Date(shift.started_at || "").toLocaleString("en-IN")}</td><td>{shift.work_area_id || "—"}</td><td><StatusPill value={shift.status}/></td><td>{shift.confidence === "INVALID" ? "Invalid — not zero" : shift.exposure_low == null ? "Pending" : `${shift.exposure_low}–${shift.exposure_high} ppm·h`}</td><td><RecordLink href={`/manager/shifts/${shift.id}`}>Open</RecordLink></td></tr>; })}</tbody></table></div></div></>;
}

function ReadingDetail({ id }: { id: string }) { const reading = mockStore.getReadings().find((item) => item.id === id); if (!reading) return <EmptyState title="Reading not found" detail="The identifier is invalid or outside company scope."/>; const reasons = Array.isArray(reading.reasons) ? reading.reasons : []; return <><PageHeader eyebrow="Immutable reading" title={reading.id} description={`${reading.reading_type} · ${new Date(reading.captured_at || "").toLocaleString("en-IN")}`}/><div className="grid gap-4 sm:grid-cols-3"><StatCard label="ΔE" value={reading.delta_e ?? "—"} note="Raw CIE76 colour difference"/><StatCard label="Cumulative estimate" value={reading.confidence === "INVALID" ? "INVALID" : reading.calibration_version_id ? `${reading.dose_low_ppm_h}–${reading.dose_high_ppm_h}` : "Unavailable"} note={reading.calibration_version_id ? "Synthetic ppm·h" : "Dose calibration unavailable"}/><StatCard label="Confidence" value={reading.confidence || "UNKNOWN"} note={reading.out_of_range ? "Outside calibration range" : "Within demo processing range"}/></div><section className="card mt-6"><h2 className="text-heading-3 text-charcoal">Quality and audit fields</h2><dl className="mt-4 grid gap-4 sm:grid-cols-2"><div><dt className="text-xs text-muted">Measurement status</dt><dd><StatusPill value={reading.measurement_status}/></dd></div><div><dt className="text-xs text-muted">Patch C status</dt><dd><StatusPill value={reading.patch_c_status}/></dd></div><div><dt className="text-xs text-muted">Calibration version</dt><dd className="text-sm text-charcoal">{reading.calibration_version_id || "Dose calibration unavailable"}</dd></div><div><dt className="text-xs text-muted">Image reference</dt><dd className="text-sm text-charcoal">{reading.image_storage_path || "No stored image"}</dd></div></dl>{reasons.length > 0 && <div className="mt-5 rounded-lg bg-amber-50 p-4"><p className="text-sm font-medium text-amber-900">Review reasons</p><ul className="mt-2 list-disc pl-5 text-sm text-amber-800">{reasons.map((reason, index) => <li key={index}>{String(reason)}</li>)}</ul></div>}</section></>; }

function RegionsPage({ detailId }: { detailId?: string }) { useDemoRevision(); const workers = mockStore.getWorkers(); const exposures = mockStore.getExposureDaily(); const regionIds = Array.from(new Set(workers.map((worker) => worker.default_region_id || "UNASSIGNED"))); const rows = regionIds.map((region) => { const ids = new Set(workers.filter((worker) => (worker.default_region_id || "UNASSIGNED") === region).map((worker) => worker.id)); const records = exposures.filter((row) => ids.has(row.worker_id)); return { region, workers: ids.size, samples: records.reduce((sum, row) => sum + (row.reading_count || 0), 0), total: Number(records.reduce((sum, row) => sum + (row.exposure_high_ppm_h || 0), 0).toFixed(1)) }; }).sort((a, b) => b.total - a.total); if (detailId) { const row = rows.find((item) => item.region === detailId); if (!row) return <EmptyState title="Region not found" detail="No company-scoped records match this region."/>; return <><PageHeader eyebrow="Recorded pattern" title={row.region} description="This page compares records associated with the region. It does not infer that the region is a continuous hotspot."/><div className="grid gap-4 sm:grid-cols-3"><StatCard label="Workers" value={row.workers} note="Default region assignments"/><StatCard label="Samples" value={row.samples} note="Timestamped reading records"/><StatCard label="Upper estimate total" value={row.total} note="Synthetic ppm·h · not concentration"/></div></>; } return <><PageHeader eyebrow="Location analysis" title="Regions / work areas" description="Ranked recorded exposure patterns from the same filtered demo records used throughout the dashboard; no continuous hotspot inference."/><div className="card"><div className="space-y-3">{rows.map((row, index) => <Link href={`/control-room/regions/${row.region}`} key={row.region} className="grid items-center gap-3 rounded-lg border border-border p-4 hover:border-border-strong sm:grid-cols-[40px_1fr_auto_auto]"><span className="text-sm text-muted">#{index + 1}</span><span className="font-medium text-charcoal">{row.region}</span><span className="text-sm text-muted">{row.samples} samples</span><span className="text-sm font-medium text-charcoal">{row.total} synthetic ppm·h</span></Link>)}</div></div></>; }

function AlertsPage() { useDemoRevision(); const [notes, setNotes] = useState<Record<string, string>>({}); const alerts = mockStore.getAlerts(); return <><PageHeader eyebrow="Supervisor review" title="Alerts" description="High and critical demo records require acknowledgement and an action note. Acknowledgement does not certify that a place is safe."/><div className="space-y-4">{alerts.map((alert) => <article key={alert.id} className="card"><div className="flex flex-wrap items-center justify-between gap-3"><div className="flex items-center gap-2"><StatusPill value={alert.severity}/><StatusPill value={alert.status}/></div><span className="text-xs text-muted">{new Date(alert.created_at || "").toLocaleString("en-IN")}</span></div><p className="mt-3 text-sm text-charcoal">{alert.message}</p>{alert.worker_id && <p className="mt-2 text-xs"><RecordLink href={`/workers/${alert.worker_id}`}>Open related worker</RecordLink></p>}{alert.status === "OPEN" && <div className="mt-4 flex flex-col gap-3 sm:flex-row"><input className="input flex-1" value={notes[alert.id] || ""} onChange={(event) => setNotes((current) => ({ ...current, [alert.id]: event.target.value }))} placeholder={alert.requires_action ? "Required action note" : "Acknowledgement note"} aria-label={`Action note for ${alert.id}`}/><button className="btn-primary" disabled={Boolean(alert.requires_action && !notes[alert.id]?.trim())} onClick={() => mockStore.acknowledgeAlert(alert.id, "u-control-01", notes[alert.id])}>Acknowledge</button></div>}{alert.status !== "OPEN" && alert.action_notes && <p className="mt-3 rounded-lg bg-canvas p-3 text-xs text-muted">Action note: {alert.action_notes}</p>}</article>)}</div></>; }

function ReportsPage() { useDemoRevision(); const [department, setDepartment] = useState("ALL"); const workers = mockStore.getWorkers(); const exposures = mockStore.getExposureDaily(); const departments = Array.from(new Set(workers.map((worker) => worker.department || "Unassigned"))).sort(); const selectedIds = new Set(workers.filter((worker) => department === "ALL" || (worker.department || "Unassigned") === department).map((worker) => worker.id)); const rows = exposures.filter((row) => selectedIds.has(row.worker_id)); const exportCsv = () => { const escape = (value: unknown) => `"${String(value ?? "").replaceAll('"', '""')}"`; const lines = ["DEMO MODE — synthetic records and simulated calibration data", ["date", "worker_code", "worker_name", "department", "low_ppm_h", "high_ppm_h", "reading_count", "shift_count"].map(escape).join(","), ...rows.map((row) => { const worker = workers.find((item) => item.id === row.worker_id); return [row.date, worker?.worker_code, worker?.full_name, worker?.department, row.exposure_low_ppm_h, row.exposure_high_ppm_h, row.reading_count, row.shift_count].map(escape).join(","); })]; const blob = new Blob([lines.join("\r\n")], { type: "text/csv;charset=utf-8" }); const url = URL.createObjectURL(blob); const link = document.createElement("a"); link.href = url; link.download = `h2s-demo-report-${department.toLowerCase().replaceAll(" ", "-")}.csv`; document.body.appendChild(link); link.click(); link.remove(); window.setTimeout(() => URL.revokeObjectURL(url), 1_000); }; return <><PageHeader eyebrow="Filtered records" title="Reports" description="Export the exact synthetic records shown by the active filter. Demo labeling is preserved inside the file."/><div className="card flex flex-col gap-3 sm:flex-row sm:items-end"><div className="flex-1"><label className="label" htmlFor="report-department">Department</label><select id="report-department" className="input" value={department} onChange={(event) => setDepartment(event.target.value)}><option value="ALL">All departments</option>{departments.map((item) => <option key={item}>{item}</option>)}</select></div><button className="btn-primary" onClick={exportCsv}>Export {rows.length} CSV records</button></div><div className="card mt-5 overflow-hidden p-0"><div className="overflow-x-auto"><table className="data-table min-w-[680px]"><thead><tr><th>Date</th><th>Worker</th><th>Department</th><th>Range</th><th>Samples</th></tr></thead><tbody>{rows.slice(0, 20).map((row) => { const worker = workers.find((item) => item.id === row.worker_id); return <tr key={row.id}><td>{row.date}</td><td>{worker?.full_name || row.worker_id}</td><td>{worker?.department || "—"}</td><td>{row.exposure_low_ppm_h}–{row.exposure_high_ppm_h} ppm·h</td><td>{row.reading_count}</td></tr>; })}</tbody></table></div></div></>; }

function AnalyticsPage() { useDemoRevision(); const exposures = mockStore.getExposureDaily(); const alerts = mockStore.getAlerts(); const bands = mockStore.getBands(); return <><PageHeader eyebrow="Analytical records" title="Analytics" description="Daily aggregates use non-overlapping valid shift increments. Records with missing baselines or invalid confidence are excluded from dose totals and remain in the reading audit trail."/><div className="grid gap-4 sm:grid-cols-3"><StatCard label="Daily aggregate rows" value={exposures.length} note="Valid synthetic increments"/><StatCard label="Alert records" value={alerts.length} note="All severities and statuses"/><StatCard label="Bands requiring attention" value={bands.filter((band) => ["WARNING", "EXPIRED", "COMPROMISED", "RETIRED"].includes(band.status || "")).length} note="Lifecycle or condition state" tone="amber"/></div><section className="card mt-6"><h2 className="text-heading-3 text-charcoal">Aggregation safeguards</h2><ul className="mt-3 list-disc space-y-2 pl-5 text-sm text-muted"><li>Latest band cumulative estimates replace earlier cumulative estimates; they are not added together.</li><li>Worker totals add only paired shift increments.</li><li>Invalid and out-of-range readings remain visible and are never rendered as zero or safe.</li><li>Dates without accepted records remain gaps.</li></ul></section></>; }

function AdminPage({ section }: { section?: string }) { const labels: Record<string, [string, string]> = { root: ["Administration", "Review company configuration and integration readiness."], users: ["Staff users", "Staff accounts derive role and company scope from authenticated server-side records."], company: ["Company", "Company identity and prototype policy settings."], locations: ["Locations", "Plants, regions, and actual work areas selected per shift."], calibration: ["Calibration", "Versioned calibration records; synthetic demo calibration is isolated from production."], thresholds: ["Alert rules", "Versioned prototype alert rules and acknowledgement requirements."], audit: ["Audit log", "Immutable operational actions and configuration changes."] }; const [title, description] = labels[section || "root"] || labels.root; return <><PageHeader eyebrow="Admin workspace" title={title} description={description}/><div className="grid gap-4 md:grid-cols-2"><section className="card"><h2 className="text-heading-3 text-charcoal">Current mode</h2><p className="mt-2 text-sm text-muted">This workspace is a synthetic, device-local demonstration. Production mutations remain unavailable until Supabase authentication, RLS tests, private image storage, and transactional functions are connected and verified.</p></section><section className="card"><h2 className="text-heading-3 text-charcoal">Prototype policy</h2><p className="mt-2 text-sm text-muted">Five working days maximum, independently checked against calendar use-by and patch condition. This is configurable policy, not a chemical-life guarantee.</p></section></div><div className="card mt-6"><h2 className="text-heading-3 text-charcoal">Configuration areas</h2><div className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{Object.entries(labels).filter(([key]) => key !== "root").map(([key, value]) => <Link key={key} href={`/admin/${key}`} className="rounded-lg border border-border p-4 hover:border-teal"><p className="font-medium text-charcoal">{value[0]}</p><p className="mt-1 text-xs text-muted">{value[1]}</p></Link>)}</div></div></>; }

export default function ResourcePage({ surface, segments }: { surface: Surface; segments: string[] }) {
  const [section, detailId] = segments;
  let content: React.ReactNode;
  if (surface === "admin") content = <AdminPage section={section}/>;
  else if (section === "workers" && detailId && detailId !== "new") content = <WorkerProfileContent workerId={detailId}/>;
  else if (section === "workers" && detailId === "new") content = <NewWorker/>;
  else if (section === "workers") content = <WorkersList basePath={`/${surface}`}/>;
  else if (section === "bands") content = <BandsPage surface={surface} detailId={detailId}/>;
  else if (section === "shifts") content = <ShiftsPage detailId={detailId}/>;
  else if (section === "reading" && detailId) content = <ReadingDetail id={detailId}/>;
  else if (section === "regions") content = <RegionsPage detailId={detailId}/>;
  else if (section === "alerts") content = <AlertsPage/>;
  else if (section === "reports") content = <ReportsPage/>;
  else if (section === "analytics") content = <AnalyticsPage/>;
  else content = <EmptyState title="Page unavailable" detail="This route is not part of the approved operational map."/>;
  return <AppShell>{content}</AppShell>;
}
